extends Node3D
## What is outside a window. Mounted into any scene that renders a room.
##
## SESSION 4r. Three rooms -- `cnc`, `obs_dome_1`, `obs_dome_2` -- rendered
## their glazing PURE BLACK, and the C&C build agent measured it at ~40% of the
## half-distance frame. The cause was never the pane: `--shot interior` builds
## one room in a local frame with nothing outside it, so behind the glass was
## `interior.tscn`'s `background_color`, which is 0.010,0.012,0.018 on purpose.
##
## This node puts the station back. Everything it draws is generated by
## `station/vista.py` from the same schema the exterior is lathed from -- the
## hull at its own LOD, expressed in the aperture's frame, with the material
## bindings the exterior scene uses -- plus a star shell generated from
## `godot/scenes/space_sky.gdshader`, the project's only statement of what
## space looks like here.
##
## THE ONE THING A PAINTED BACKDROP CANNOT DO, and the reason this is geometry
## rather than a texture: the station SPINS, at 33.4716 s a revolution. The
## hull is fixed in the station's frame and the stars are fixed in the inertial
## frame, so the same window shows the same hull against different stars as the
## ring turns. `set_phase()` is that, and `station/vista.py --selftest` asserts
## the two bases differ by exactly Rz(-90) over a quarter turn.
##
## WHAT IT DOES NOT DO YET, said plainly because this project has produced
## "finished machinery with no caller on the shipped path" nine times: this is
## mounted by `render_shot.gd`, which is the render path. The shipped build
## (`main.gd` -> `stream.gd`) does not call it. The patch is one line and is in
## the session report; until it lands, a player walking to a window still sees
## black and only a render shows the view.

## Visual layer the vista lives on. Its own layer so the vista's sun lights the
## station outside and nothing else, and so the room's own fitting lights --
## which `render_shot.gd` spawns with an all-layers cull mask -- do not reach
## 8 km down the hull. 20 is chosen to sit clear of the layers `walk.gd` uses
## for collision; visual layers and physics layers are separate registers in
## Godot but sharing a number between them reads as a bug to the next person.
const VISTA_LAYER := 20

var _stars: MeshInstance3D
var _hull: Node3D
var _sun: DirectionalLight3D
var _manifest: Dictionary = {}
var _phase: float = 0.0


## Mount the vista for one room. `dir` is the directory
## `station/vista.py --build` wrote into. Returns false and says why if there
## is nothing to mount -- a room with no window is the normal case, not an
## error.
static func mount(parent: Node3D, room: String, dir: String,
		phase_deg: float = -1.0, gain: float = 1.0) -> Node:
	var path := dir.path_join(room + ".json")
	if not FileAccess.file_exists(path):
		print("vista: no view for '%s' (%s absent) -- the room renders with "
			% [room, path] + "whatever is behind its glass, which for a "
			+ "window is the background colour")
		return null
	var f := FileAccess.open(path, FileAccess.READ)
	var parsed = JSON.parse_string(f.get_as_text())
	if typeof(parsed) != TYPE_DICTIONARY:
		push_error("vista: %s is not a JSON object" % path)
		return null
	var node := load("res://scripts/vista.gd").new() as Node3D
	node.name = "Vista"
	parent.add_child(node)
	node._build(parsed, phase_deg, gain)
	return node


func _build(man: Dictionary, phase_deg: float, gain: float) -> void:
	_manifest = man
	_load_hull(man)
	_load_stars(man)
	_add_sun(man, gain)
	set_phase(phase_deg)
	print("vista: %s -- %d hull triangles, %d groups, station fills %.3f of "
		% [man.get("place", "?"), int(man.get("triangles", 0)),
			(man.get("groups", []) as Array).size(),
			float(man.get("station_frac", 0.0))]
		+ "the window (the show's frame gives %.3f), spin phase %.1f deg "
		% [float(man.get("station_frac_ref", 0.0)), _phase]
		+ "(%.2f s into a %.2f s revolution)"
		% [_phase / 360.0 * float(man.get("spin_period_s", 33.471574)),
			float(man.get("spin_period_s", 33.471574))])


func _load_hull(man: Dictionary) -> void:
	_hull = Node3D.new()
	_hull.name = "Hull"
	add_child(_hull)
	var glb := String(man.get("glb", ""))
	if glb == "" or not FileAccess.file_exists(glb):
		push_error("vista: %s declares no hull geometry at '%s'. The view "
			% [man.get("place", "?"), glb] + "would be stars over nothing, "
			+ "which is the defect this node exists to remove.")
		return
	var doc := GLTFDocument.new()
	var state := GLTFState.new()
	if doc.append_from_file(glb, state) != OK:
		push_error("vista: glTF load failed for %s" % glb)
		return
	var scene := doc.generate_scene(state)
	_hull.add_child(scene)
	# MATERIALS COME FROM THE LIBRARY, BY NAME, AND THE NAMES COME FROM THE
	# LIBRARY TOO. `station/vista.py` writes `materials` as
	# {mesh group: material name} out of `materials.godot_rules("exterior")`,
	# so the hull seen through a window carries the same surfaces as the hull
	# seen from outside it. A second table here would be a second opinion.
	var rules: Dictionary = man.get("materials", {})
	var missing := {}
	var n := 0
	for mi in _mesh_instances(scene):
		var key := String(mi.name)
		var chosen: Material = null
		var best := -1
		for frag in rules:
			if key.contains(String(frag)) and String(frag).length() > best:
				var res := "res://materials/%s.tres" % String(rules[frag])
				var mat := load(res) as Material
				if mat != null:
					chosen = mat
					best = String(frag).length()
				else:
					missing[res] = true
		if chosen != null:
			for i in mi.mesh.get_surface_count():
				mi.set_surface_override_material(i, chosen)
			n += 1
		else:
			missing[key] = true
		mi.layers = 1 << (VISTA_LAYER - 1)
		# The station outside is not a shadow caster in here: the only light
		# that reaches it is the vista sun, and a shadow map covering 8 km of
		# hull on a CPU rasteriser is minutes a frame for a shadow the window
		# cannot show.
		mi.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
	if missing.size() > 0:
		print("vista: %d group(s)/material(s) unresolved: %s"
			% [missing.size(), ", ".join(PackedStringArray(missing.keys()))])
	print("vista: %d hull mesh instance(s) materialled" % n)


func _load_stars(man: Dictionary) -> void:
	var path := String(man.get("star_shader", ""))
	if not FileAccess.file_exists(path):
		push_error("vista: no star shader at '%s'" % path)
		return
	var sh := Shader.new()
	sh.code = FileAccess.get_file_as_string(path)
	var mat := ShaderMaterial.new()
	mat.shader = sh
	# A SHELL, NOT A SKY. `space_sky.gdshader` is `shader_type sky` and can only
	# be mounted on an Environment, which would change the ambient and the
	# reflections of every interior frame in the project -- 23 of them are gated
	# on their distribution by `tools/measure_frame.py`. So the same star field
	# runs on a sphere the camera sits inside, drawn unshaded with depth writes
	# off, and the room and the hull occlude it in the ordinary way.
	#
	# The radius is beyond `view_range_m` so nothing the vista draws is ever
	# outside it, and inside the camera's far plane so it is not clipped away.
	var sphere := SphereMesh.new()
	sphere.radial_segments = 32
	sphere.rings = 16
	var r: float = min(float(man.get("view_range_m", 12000.0)) * 1.2, 16000.0)
	sphere.radius = r
	sphere.height = r * 2.0
	_stars = MeshInstance3D.new()
	_stars.name = "Stars"
	_stars.mesh = sphere
	_stars.material_override = mat
	_stars.layers = 1 << (VISTA_LAYER - 1)
	_stars.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
	_stars.extra_cull_margin = minf(r, 16384.0)
	add_child(_stars)


func _add_sun(man: Dictionary, gain: float) -> void:
	_sun = DirectionalLight3D.new()
	_sun.name = "VistaSun"
	add_child(_sun)
	var d: Array = man.get("sun_dir_room", [0.0, 1.0, 0.0])
	var dir := Vector3(float(d[0]), float(d[1]), float(d[2])).normalized()
	# A DirectionalLight3D emits along its own -Z, so a surface facing back
	# toward `dir` is the one that gets lit -- the same convention
	# `render_shot.gd::_aim_sun` uses, and worth stating because getting it
	# backwards lights the far side of the station and still looks like light.
	_sun.look_at_from_position(dir * 1000.0, Vector3.ZERO,
		Vector3.UP if absf(dir.y) < 0.9 else Vector3.RIGHT)
	# ONLY THE VISTA. Without this the sun would light the room's interior
	# through its own walls' back faces and the frame would be an outdoor shot.
	_sun.light_cull_mask = 1 << (VISTA_LAYER - 1)
	# The energy is DATA, solved in `station/vista.py` against the reference
	# frame's glazing-over-bulkhead ratio and written into the manifest;
	# `gain` is the A/B knob on top of it and is 1.0 in every shipped frame.
	_sun.light_energy = float(man.get("sun_energy", 1.0)) * gain
	_sun.shadow_enabled = false


## Turn the sky to the station's spin phase. The hull does not move: it is
## fixed in the station's frame and only the stars are inertial.
func set_phase(phase_deg: float) -> void:
	if _stars == null:
		return
	if phase_deg < 0.0:
		phase_deg = float(_manifest.get("phase_deg", 0.0))
	_phase = phase_deg
	var b: Array = _manifest.get("sky_basis", [])
	var basis := Basis.IDENTITY
	if b.size() == 3:
		# `station/vista.py` writes the matrix ROW BY ROW; Godot's
		# `Basis(x, y, z)` takes the three COLUMNS, so the read transposes.
		# Stated rather than left to be inferred: both readings produce a
		# perfectly plausible starfield and only one of them is the sky this
		# window looks at.
		basis = Basis(Vector3(b[0][0], b[1][0], b[2][0]),
			Vector3(b[0][1], b[1][1], b[2][1]),
			Vector3(b[0][2], b[1][2], b[2][2]))
	# The station turns +phi about its own +Z, so the sky turns -phi in the
	# window. Applied ONCE, here: `build` writes the basis at phase zero for
	# exactly this reason.
	var spin := Basis(Vector3(0, 0, 1), -deg_to_rad(phase_deg))
	var b2 := basis * spin
	if absf(b2.determinant() - 1.0) > 1e-6:
		push_error("vista: sky basis determinant %.6f -- that is a "
			% b2.determinant() + "reflection, and a mirrored starfield looks "
			+ "exactly like a starfield.")
		return
	_stars.transform = Transform3D(b2, Vector3.ZERO)


func _mesh_instances(n: Node, out: Array[MeshInstance3D] = []) -> Array[MeshInstance3D]:
	if n is MeshInstance3D and (n as MeshInstance3D).mesh != null:
		out.append(n)
	for c in n.get_children():
		_mesh_instances(c, out)
	return out


## Make the room's glazing transmissive.
##
## A SHIM WITH A STATED REMOVAL CONDITION, and it says so rather than pretending
## to be the design. `materials.viewport_glazing` is OPAQUE -- albedo
## 0.040,0.042,0.046, roughness 0.07, specular 0.92 -- and
## `station/materials.py`'s `Material` class has no transparency field at all,
## so there is nowhere in the library to say "this surface is glass". Until it
## grows one (the patch is in the session report), the transmission is applied
## here, DERIVED from the library's own entry rather than replacing it: the
## material is duplicated, every measured value is kept, and only alpha is set,
## from `pane_transmittance` in the manifest -- 0.840, which is
## (1 - 0.0426)^4, four air-glass interfaces at n = 1.52.
##
## When the library carries transparency this function finds the pane already
## transmissive and says so instead of acting.
static func glaze(root: Node, man: Dictionary) -> int:
	var groups: Array = man.get("glazing_groups", [])
	var t := float(man.get("pane_transmittance", 0.84))
	var n := 0
	var already := 0
	for mi in _all_mesh_instances(root):
		var key := String(mi.name)
		var hit := false
		for g in groups:
			if key.contains(String(g)):
				hit = true
		if not hit:
			continue
		for i in mi.mesh.get_surface_count():
			var m := mi.get_surface_override_material(i)
			if m == null:
				m = mi.mesh.surface_get_material(i)
			if m == null or not (m is StandardMaterial3D):
				continue
			var sm := (m as StandardMaterial3D)
			if sm.transparency != BaseMaterial3D.TRANSPARENCY_DISABLED:
				already += 1
				continue
			var dup := sm.duplicate() as StandardMaterial3D
			dup.transparency = BaseMaterial3D.TRANSPARENCY_ALPHA
			var c := dup.albedo_color
			dup.albedo_color = Color(c.r, c.g, c.b, 1.0 - t)
			# A pane you look through does not write depth over the view.
			dup.depth_draw_mode = BaseMaterial3D.DEPTH_DRAW_OPAQUE_ONLY
			mi.set_surface_override_material(i, dup)
			n += 1
	print("vista: glazing -- %d pane surface(s) made transmissive at T=%.3f, "
		% [n, t] + "%d already transmissive in the library" % already)
	return n


static func _all_mesh_instances(n: Node, out: Array[MeshInstance3D] = []) -> Array[MeshInstance3D]:
	if n is MeshInstance3D and (n as MeshInstance3D).mesh != null:
		out.append(n)
	for c in n.get_children():
		_all_mesh_instances(c, out)
	return out
