#!/usr/bin/env python3
"""Bake the two sidecars that make a deck's people alive, for EVERY deck.

    python3 tools/bake_sidecars.py            # bake whatever is missing
    python3 tools/bake_sidecars.py --check    # report only, write nothing
    python3 tools/bake_sidecars.py --force    # rebuild everything
    python3 tools/bake_sidecars.py --stale    # rebuild what predates its cast
    python3 tools/bake_sidecars.py --only 'blue_*'

WHAT WAS MISSING AND WHY IT MATTERED.  The whole-station export
(`tools/export_station.py` + `tools/bake_station.py`) writes five artefacts a
deck -- mesh, collision shell, cast, crowd placements, interactables -- and
neither of the two SIDECARS.  Those were produced by the single-deck path
(`station/walkable.py --deck`, then `station/dialogue.py --sidecar`, then
`arrival.write_arrival_sidecar`), which by definition ran on one deck.  So the
station shipped with 70 decks and ONE of them, `blue_0_0`, had a dialogue file.

`godot/scripts/walk.gd::_wire_dialogue` returns the moment `dialogue_path` is
empty or absent -- it prints `dialogue: no sidecar at %s` and leaves every actor
without an exchange.  `station/boot.py::build` sets that key from
`sidecar(stem, "_dialogue.json")`, which returns "" when the file is not there,
and `godot/scripts/main.gd::_boot_manifest` derives the same name when the
manifest omits it.  All three agree on where the file lives and all three
degrade silently when it does not exist.  Measured on this tree before this
tool ran: 363 of the station's 4,563 cast members had anything to say.

THIS TOOL GENERATES NOTHING ITSELF.  Both sidecars have a generator already and
reimplementing either would be a second copy of a derivation -- the defect
CLAUDE.md records against cached collision totals and committed frames.  So:

    dialogue   `station/dialogue.py::write_sidecar`, at SIDECAR_HOURS
               (03:00, 09:00, 13:00, 19:00 -- one row per person per hour, so
               the same person is asked at four points of their own schedule)
    arrival    `station/arrival.py::write_arrival_sidecar`, with the `paths`
               block assembled from the artefacts already on disk

AND THE ARRIVAL `paths` BLOCK IS ASSEMBLED, NOT REBUILT.  `arrival.py`'s own
caller for it is `build_playable_deck`, which rebuilds the deck's render mesh,
collision shell and cast from the schema -- twenty-plus minutes a deck, and it
writes into `station/generated/scene/deck`, which is the WRONG directory for a
streamed station build.  Every field that block needs is already sitting beside
the mesh:

    glb/collision/interact/actors   the files themselves
    rooms                           the distinct `place` of the baked cast,
                                    which is what `station/boot.py::build`
                                    reads for the same field
    spawn                           `boot.spawn_from_shell` on the collision
                                    shell's own floor group -- the derivation
                                    `boot.py` uses for the shipped boot.json,
                                    called rather than copied
    spawn_at                        the nearest cast member's room if one is
                                    within `boot.NEAR_ROOM_M`, else "corridor"

VERIFIED AGAINST THE ONE DECK THAT ALREADY HAD BOTH.  Re-running this assembly
for `blue_0_0` and diffing against the sidecar the main agent generated by the
full path gives a BYTE-IDENTICAL file (md5 af5edea85f856dce592c1ac4e6e722a8),
and the derived spawn is `[2.7156, 211.4581, 7447.0716]` against a committed
`[2.7156, 211.4581, 7447.0716]`.  That is the evidence the shortcut is the same
answer as the long way round, and it is why `blue_0_0` is skipped by default
rather than trusted by assertion.

ONE SEQUENCE, SEVENTY BUILDS -- ON PURPOSE.  The sidecars differ only in their
`build` block.  The arrival sequence is the PLAYER's first ten minutes and there
is one player; varying the seed per deck would mean the player's name, species
and ship changed depending on which deck the game happened to boot on.
`godot/scripts/arrival.gd::_adopt_build` takes the build block and nothing else
from the file, so what a per-deck copy buys is exactly what it needs to buy: a
sequence that names ITS OWN deck's mesh and a spawn point on ITS OWN floor.
`--seed`/`--day` change it for anyone who wants otherwise.

IDEMPOTENT, RESUMABLE, AND ATOMIC -- because this container recycles.  A deck
whose sidecar exists is skipped, so a killed run resumes where it stopped.  And
every file is written to a temporary directory and `os.replace`d into place, so
a run killed mid-write leaves the old file or no file, never half a file that
the next run would count as done.  A half-written sidecar is worse than a
missing one: the missing one gets rebuilt.
"""
import argparse
import fnmatch
import glob
import json
import math
import os
import shutil
import sys
import tempfile
import time

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(ROOT, "station"))
sys.path.insert(0, HERE)


# ===========================================================================
# 1.  What is on disk
# ===========================================================================
def deck_dir(explicit=None):
    """Where the decks are.

    Defaults to `boot.preferred_deck_dir()` rather than to a constant, so this
    tool bakes for the same build the game boots from.  That function's rule is
    "the streamed build wins whenever it exists", and hard-coding the streamed
    directory here would put the two in disagreement the first time somebody
    ran a single-deck build.
    """
    if explicit:
        return os.path.abspath(explicit)
    import boot                                                  # noqa: PLC0415
    return boot.preferred_deck_dir()


def stems(dd, only=None):
    """Every deck in `dd` that has a cast, newest-name-first order aside.

    THE CAST FILE IS THE KEY, not the mesh.  A dialogue sidecar is a function of
    the actors list and nothing else, and an arrival sidecar needs the cast for
    its room list -- so a deck with a mesh and no `_actors.json` is a deck this
    tool has nothing to say about, and it is reported as such rather than
    counted as done.
    """
    out = []
    for p in sorted(glob.glob(os.path.join(dd, "*_actors.json"))):
        stem = os.path.basename(p)[: -len("_actors.json")]
        if only and not any(fnmatch.fnmatch(stem, o) for o in only):
            continue
        out.append(stem)
    return out


def meshless(dd, only=None):
    """Decks with a mesh but no cast -- named, so they are not silently absent.

    A count of "70 done" over a directory holding 74 decks is the kind of number
    this project's own rules forbid: the denominator has to be visible.
    """
    out = []
    for p in sorted(glob.glob(os.path.join(dd, "*.glb"))):
        stem = os.path.basename(p)[:-4]
        if stem.endswith("_col") or stem.endswith("_collision"):
            continue
        if only and not any(fnmatch.fnmatch(stem, o) for o in only):
            continue
        if not os.path.exists(os.path.join(dd, stem + "_actors.json")):
            out.append(stem)
    return out


def collision_of(dd, stem):
    """The collision shell beside `stem`, in the order `boot.py` prefers.

    Two spellings ship -- `_col.glb` from the single-deck path and
    `_collision.glb` from the whole-station export -- and `boot.collision_shell`
    prefers the first and falls back to the second.  The same order is used
    here so the path written into the arrival sidecar is the path the boot
    manifest names for the same deck.
    """
    for suffix in ("_col.glb", "_collision.glb"):
        p = os.path.join(dd, stem + suffix)
        if os.path.exists(p):
            return p
    return ""


# ===========================================================================
# 2.  Writing, atomically
# ===========================================================================
class Scratch:
    """A temp directory that survives being on a different filesystem."""

    def __init__(self):
        self.path = tempfile.mkdtemp(prefix="bake_sidecars_")

    def install(self, src, dst):
        """Move `src` onto `dst`, atomically when the filesystem allows it."""
        try:
            os.replace(src, dst)
        except OSError:
            # Different device: `shutil.move` copies then unlinks.  Not atomic,
            # and the only case where a kill can leave a partial file -- said
            # here rather than assumed away.
            shutil.move(src, dst)

    def close(self):
        shutil.rmtree(self.path, ignore_errors=True)


# ===========================================================================
# 3.  The two bakes
# ===========================================================================
def bake_dialogue(dd, stem, scratch, hour=13.0, day=0):
    """`dialogue.write_sidecar` on this deck's cast.  Returns the row count."""
    import dialogue                                              # noqa: PLC0415
    actors = os.path.join(dd, stem + "_actors.json")
    tmp = os.path.join(scratch.path, stem + "_dialogue.json")
    n = dialogue.write_sidecar(actors, tmp, dialogue.World(hour=hour, day=day))
    scratch.install(tmp, os.path.join(dd, stem + "_dialogue.json"))
    return n


def spawn_for_deck(dd, stem, scratch):
    """(spawn, spawn_at, detail) for `stem`, off its own collision shell.

    THE DERIVATION IS `boot.spawn_from_shell` AND IT IS CALLED, NOT COPIED --
    the docstring there records what a hand-rolled version cost ("the centroid
    of an arc is inside the circle it bends around", a spawn 214 m from any
    floor, a body falling for two minutes).  What is done here is only the
    format conversion it needs: it reads named groups out of an OBJ and the
    whole-station export writes only GLB.

    AND THE OBJ IS WRITTEN TO A TEMP DIRECTORY, NOT BESIDE THE DECK.
    `boot.collision_shell` caches it next to the mesh, which is right for
    `boot.py` and wrong here: this tool has one job and adding 70 multi-megabyte
    files to a directory other agents are reading is not it.
    """
    import boot                                                  # noqa: PLC0415
    import glb_to_obj as g2o                                     # noqa: PLC0415
    glb = collision_of(dd, stem)
    if not glb:
        raise SystemExit("bake_sidecars: %s has no collision shell in %s"
                         % (stem, dd))
    obj = os.path.join(scratch.path, stem + "_col.obj")
    g2o.write_obj(obj, g2o.read_glb(glb), rename=g2o.collision_group)
    spawn, detail = boot.spawn_from_shell(obj)
    os.remove(obj)
    return spawn, detail


def spawn_room(dd, stem, spawn):
    """Which room the spawn is in, or "corridor".

    `station/boot.py::build`'s rule, and its comment is the reason for the
    distance test: "the nearest person on the deck is always SOMEBODY, and
    calling their room the spawn's room put `in arrival_concourse` on a point
    160 m down the corridor from it".
    """
    import boot                                                  # noqa: PLC0415
    with open(os.path.join(dd, stem + "_actors.json")) as f:
        cast = json.load(f)
    if not cast:
        return "corridor"
    near = min(cast, key=lambda a: (a.get("x", 0) - spawn[0]) ** 2
               + (a.get("y", 0) - spawn[1]) ** 2
               + (a.get("z", 0) - spawn[2]) ** 2)
    d = math.dist(spawn, [near.get("x", 0), near.get("y", 0), near.get("z", 0)])
    return near.get("place", "corridor") if d <= boot.NEAR_ROOM_M else "corridor"


def rooms_of(dd, stem):
    with open(os.path.join(dd, stem + "_actors.json")) as f:
        return sorted({a.get("place", "") for a in json.load(f)
                       if a.get("place")})


def bake_arrival(dd, stem, scratch, day=0, seed="player"):
    """`arrival.write_arrival_sidecar` with a `paths` block read off disk."""
    import arrival                                               # noqa: PLC0415
    spawn, _detail = spawn_for_deck(dd, stem, scratch)
    paths = {
        "stem": stem, "dir": dd,
        "glb": os.path.join(dd, stem + ".glb"),
        "collision": collision_of(dd, stem),
        "interact": os.path.join(dd, stem + "_interact.json"),
        "actors": os.path.join(dd, stem + "_actors.json"),
        "spawn": [round(v, 4) for v in spawn],
        "spawn_at": spawn_room(dd, stem, spawn),
        "rooms": rooms_of(dd, stem),
    }
    written = arrival.write_arrival_sidecar(scratch.path, stem, paths,
                                            day=day, seed=seed)
    scratch.install(written, os.path.join(dd, stem + "_arrival.json"))
    return paths


# ===========================================================================
# 4.  Reporting -- with denominators
# ===========================================================================
def dialogue_state(dd, stem):
    """(status, rows, spoke, cast) for this deck's dialogue sidecar.

    `dialogue.coverage` is the authority on "can speak", not a count written
    here: it intersects the cast's groups with the sidecar's, which is the same
    join `walk.gd::_wire_dialogue` does at runtime.
    """
    import dialogue                                              # noqa: PLC0415
    a = os.path.join(dd, stem + "_actors.json")
    d = os.path.join(dd, stem + "_dialogue.json")
    if not os.path.exists(d):
        return "MISSING", 0, 0, 0
    try:
        with open(d) as f:
            rows = json.load(f)
    except (ValueError, OSError) as e:
        return "UNREADABLE(%s)" % type(e).__name__, 0, 0, 0
    spoke, cast, _silent = dialogue.coverage(a, d)
    stale = os.path.getmtime(d) < os.path.getmtime(a)
    status = "STALE" if stale else ("ok" if spoke == cast else "SILENT")
    return status, len(rows), spoke, cast


def arrival_state(dd, stem):
    """(status, steps, note) for this deck's arrival sidecar.

    The check that matters is not "does the file exist" but "does its build
    block name files that are here".  `arrival.gd::_adopt_build` REPLACES the
    glb, collision, interact and actors paths with the sidecar's own, so a
    sidecar naming another machine's tree is a sidecar that loads no deck --
    the failure `main.gd::_rebased_sidecar` was written for.
    """
    p = os.path.join(dd, stem + "_arrival.json")
    if not os.path.exists(p):
        return "MISSING", 0, ""
    try:
        with open(p) as f:
            seq = json.load(f)
    except (ValueError, OSError) as e:
        return "UNREADABLE(%s)" % type(e).__name__, 0, ""
    if "steps" not in seq:
        return "NO STEPS", 0, ""
    b = seq.get("build") or {}
    gone = [k for k in ("glb", "collision", "interact", "actors")
            if not (b.get(k) and os.path.exists(b[k]))]
    if gone:
        return "DANGLING", len(seq["steps"]), "names no " + ", ".join(gone)
    if os.path.basename(str(b.get("glb", ""))) != stem + ".glb":
        return "WRONG DECK", len(seq["steps"]), "build names %s" % b.get("glb")
    sp = b.get("spawn")
    if not (isinstance(sp, list) and len(sp) == 3):
        return "NO SPAWN", len(seq["steps"]), ""
    if math.hypot(sp[0], sp[1]) < 1.0:
        # `arrival.py::write_arrival_sidecar`'s own opening warning: on a ring
        # deck at radius 211 m, 0,0,0 is the SPIN AXIS and the body falls for
        # two minutes.  Cheap to assert, and it names the failure mode.
        return "SPAWN ON AXIS", len(seq["steps"]), ""
    return "ok", len(seq["steps"]), ""


def verify_spawn(dd, stem, scratch, tol=0.01):
    """Re-derive the spawn and compare it with the one in the sidecar.

    `boot.check` does exactly this for the booted deck and calls agreement
    "evidence rather than tautology" because the two numbers come from
    different code paths.  Here both come from `spawn_from_shell`, so what it
    proves is narrower and worth stating: that the file on disk still describes
    the collision shell beside it.  A shell rebuilt after its sidecar moves the
    floor and nothing else would notice.
    """
    p = os.path.join(dd, stem + "_arrival.json")
    if not os.path.exists(p):
        return None
    with open(p) as f:
        have = (json.load(f).get("build") or {}).get("spawn")
    if not (isinstance(have, list) and len(have) == 3):
        return None
    want, _ = spawn_for_deck(dd, stem, scratch)
    return math.dist(have, want)


# ===========================================================================
# 5.  The run
# ===========================================================================
def run(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0],
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--dir", help="deck directory (default: the one "
                                  "station/boot.py would boot from)")
    ap.add_argument("--only", action="append",
                    help="glob over deck stems; repeatable")
    ap.add_argument("--check", action="store_true",
                    help="report what is there and write nothing")
    ap.add_argument("--force", action="store_true",
                    help="rebuild sidecars that already exist")
    ap.add_argument("--stale", action="store_true",
                    help="rebuild sidecars older than their own actors file")
    ap.add_argument("--verify-spawn", action="store_true",
                    help="with --check: re-derive every spawn off its shell "
                         "and compare (about half a second a deck)")
    ap.add_argument("--dialogue-only", action="store_true")
    ap.add_argument("--arrival-only", action="store_true")
    ap.add_argument("--hour", type=float, default=13.0,
                    help="dialogue World hour; the sidecar bakes "
                         "SIDECAR_HOURS regardless, this sets day-of")
    ap.add_argument("--day", type=int, default=0)
    ap.add_argument("--seed", default="player",
                    help="arrival sequence seed -- ONE sequence for the whole "
                         "station by default; see the module docstring")
    a = ap.parse_args(argv)

    dd = deck_dir(a.dir)
    if not os.path.isdir(dd):
        print("bake_sidecars: no deck directory at %s" % dd)
        return 2
    todo = stems(dd, a.only)
    no_cast = meshless(dd, a.only)
    print("bake_sidecars: %s" % dd)
    print("  %d decks with a cast, %d meshes without one"
          % (len(todo), len(no_cast)))
    if no_cast:
        # NAMED, NOT NETTED OUT.  These are not failures and they are not
        # successes either; a deck with no `_actors.json` has nobody to speak.
        print("  no cast, so nothing to bake: %s" % ", ".join(no_cast))
    if not todo:
        print("bake_sidecars: nothing to do")
        return 0

    want_d = not a.arrival_only
    want_a = not a.dialogue_only
    scratch = Scratch()
    t0 = time.time()
    built_d = built_a = skipped_d = skipped_a = 0
    failed = []
    try:
        for i, stem in enumerate(todo, 1):
            actors = os.path.join(dd, stem + "_actors.json")
            with open(actors) as f:
                n_cast = len(json.load(f))
            marks = []
            for kind, want, baker in (
                    ("dialogue", want_d, bake_dialogue),
                    ("arrival", want_a, bake_arrival)):
                path = os.path.join(dd, "%s_%s.json" % (stem, kind))
                here = os.path.exists(path)
                old = here and os.path.getmtime(path) < os.path.getmtime(actors)
                if not want:
                    continue
                if here and not a.force and not (a.stale and old):
                    marks.append("%s skip%s" % (kind[:4], "(STALE)" if old else ""))
                    if kind == "dialogue":
                        skipped_d += 1
                    else:
                        skipped_a += 1
                    continue
                if a.check:
                    marks.append("%s WOULD BAKE" % kind[:4])
                    continue
                t = time.time()
                try:
                    if kind == "dialogue":
                        n = baker(dd, stem, scratch, hour=a.hour, day=a.day)
                        marks.append("dial %d rows %.1fs" % (n, time.time() - t))
                        built_d += 1
                    else:
                        baker(dd, stem, scratch, day=a.day, seed=a.seed)
                        marks.append("arri %.1fs" % (time.time() - t))
                        built_a += 1
                except Exception as e:                    # noqa: BLE001
                    marks.append("%s FAILED %s: %s"
                                 % (kind[:4], type(e).__name__, e))
                    failed.append((stem, kind, "%s: %s" % (type(e).__name__, e)))
            if marks and not a.check:
                print("  [%2d/%2d] %-16s %4d cast   %s"
                      % (i, len(todo), stem, n_cast, "  ".join(marks)))
    finally:
        scratch.close()

    # -------------------------------------------------------------- the ledger
    print("")
    print("  %-16s %-9s %6s %6s %6s   %-9s %5s" % (
        "deck", "dialogue", "rows", "spoke", "cast", "arrival", "steps"))
    rows = spoke = cast = 0
    bad = []
    scratch = Scratch()
    try:
        for stem in todo:
            ds, dr, dsp, dc = dialogue_state(dd, stem)
            as_, ast, note = arrival_state(dd, stem)
            rows += dr
            spoke += dsp
            cast += dc
            extra = ""
            if a.check and a.verify_spawn:
                off = verify_spawn(dd, stem, scratch)
                if off is not None:
                    extra = "  spawn %s off %.4f m" % (
                        "ok" if off < 0.01 else "DRIFTED", off)
                    if off >= 0.01:
                        bad.append("%s spawn drifted %.3f m" % (stem, off))
            if ds != "ok" or as_ != "ok":
                bad.append("%s dialogue=%s arrival=%s %s"
                           % (stem, ds, as_, note))
            print("  %-16s %-9s %6d %6d %6d   %-9s %5d %s%s"
                  % (stem, ds, dr, dsp, dc, as_, ast, note, extra))
    finally:
        scratch.close()

    dt = time.time() - t0
    print("")
    print("bake_sidecars: %d decks, %d dialogue exchanges, "
          "%d of %d people can speak (%.1f%%)"
          % (len(todo), rows, spoke, cast,
             100.0 * spoke / cast if cast else 0.0))
    print("  baked %d dialogue + %d arrival, skipped %d + %d, %.1f s"
          % (built_d, built_a, skipped_d, skipped_a, dt))
    if failed:
        for stem, kind, why in failed:
            print("  FAILED %s %s -- %s" % (stem, kind, why))
    if bad:
        print("  NOT COMPLETE:")
        for b in bad:
            print("    %s" % b)
        return 1
    print("  every deck with a cast has both sidecars, and every cast member "
          "in them has something to say")
    return 0


if __name__ == "__main__":                                   # pragma: no cover
    raise SystemExit(run())
