#!/usr/bin/env python3
"""Generate and validate the completion registry from the spec annexes.

THE-STATION.md §1's whole authority rests on this file existing and running:
*"a gate that does not run is not a gate, and today the entire §1 is one"* was
the synthesis judge's verdict on the bible before this existed. This is the
machinery that turns three markdown annexes into `spec/completion.yaml` and
FAILS on every ambiguity a future session could have exploited:

  * an item without an acceptance check fails the generator (not the item — the
    GENERATOR, so the registry cannot be produced around it)
  * every cross-reference (SHB-nn.x letters, INC/SYS/PLC/FAC/ROLE citations)
    must resolve to a defined item — the six broken pointers the panel found
    become build failures, permanently
  * the docs and the registry are a bijection: an item in the docs missing from
    the registry, or vice versa, fails
  * item text is hashed; editing an adopted item without a SPEC-CHANGE entry
    whose `recomputes:` names it fails (the freeze, enforced rather than asked)

The registry rows carry a `harness` field: `existing-tool` (a named command a
session can run today), `tool-to-build` (the check is real but its harness is
not written — the row is RED by definition until it is), or `AUDIT` (the
randomised human-shaped audit is the harness). `station/spec_check.py` refuses
to report GREEN for any row whose harness it does not actually implement, so
"prose a future session reads selectively" is structurally over.
"""
import argparse
import hashlib
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOCS = [
    "docs/THE-STATION.md",
    "docs/spec/PLACES.md",
    "docs/spec/PEOPLE.md",
    "docs/spec/SYSTEMS.md",
]
OUT = os.path.join(ROOT, "spec/completion.yaml")

# Item IDs. Lettered sub-rows (SHB-08.a) attach to their parent. CAST-02's 50
# roster rows green only when all children green (the umbrella rule).
ID_RE = re.compile(
    r"\b(PLC|SHB|SHC|INC|FAC|CAST|ROLE|DLG|SYS|SUR|PLY)-(\d{1,3})([a-z]|\.[a-z])?\b")
DEF_RE = re.compile(
    r"^#{2,4}\s+.*?\b(PLC|SHB|SHC|INC|FAC|CAST|ROLE|DLG|SYS|SUR|PLY)-(\d{1,3})\b"
    r"|^\*\*(PLC|SHB|SHC|INC|FAC|CAST|ROLE|DLG|SYS|SUR|PLY)-(\d{1,3})")
CHECK_RE = re.compile(r"\*\*(CHECK|ACCEPT|Check)[:\s]", re.I)
HARNESS_RE = re.compile(r"harness:\s*([A-Za-z0-9_./ -]+)")


def parse(paths):
    """(items, refs, errors). Items keyed by canonical ID."""
    items, refs, errors = {}, [], []
    for rel in paths:
        p = os.path.join(ROOT, rel)
        if not os.path.exists(p):
            errors.append(f"{rel}: MISSING FILE")
            continue
        cur, buf, start = None, [], 0
        for n, ln in enumerate(open(p, encoding="utf-8"), 1):
            m = DEF_RE.match(ln)
            if m:
                if cur:
                    items[cur]["end"] = n - 1
                    items[cur]["text"] = "".join(buf)
                g = m.groups()
                pref, num = (g[0], g[1]) if g[0] else (g[2], g[3])
                cur = f"{pref}-{int(num):03d}"
                if cur in items:
                    errors.append(f"{rel}:{n}: DUPLICATE definition of {cur} "
                                  f"(first at {items[cur]['file']}:{items[cur]['line']})")
                    cur = f"{cur}#dup{n}"
                items[cur] = {"file": rel, "line": n, "text": "", "end": n}
                buf, start = [ln], n
            elif cur:
                buf.append(ln)
            for rm in ID_RE.finditer(ln):
                refs.append((rel, n, f"{rm.group(1)}-{int(rm.group(2)):03d}"))
        if cur:
            items[cur]["end"] = n
            items[cur]["text"] = "".join(buf)
    return items, refs, errors


def validate(items, refs):
    errors = []
    defined = set(items)
    for rel, n, rid in refs:
        if rid not in defined:
            errors.append(f"{rel}:{n}: reference to UNDEFINED item {rid}")
    for iid, it in items.items():
        if "#dup" in iid:
            continue
        if not CHECK_RE.search(it["text"]):
            errors.append(f"{it['file']}:{it['line']}: {iid} has NO acceptance "
                          f"check — the generator refuses to registry it")
    return errors


def emit(items):
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    rows = []
    for iid in sorted(k for k in items if "#dup" not in k):
        it = items[iid]
        hm = HARNESS_RE.search(it["text"])
        harness = hm.group(1).strip() if hm else "tool-to-build"
        digest = hashlib.sha256(it["text"].encode()).hexdigest()[:16]
        rows.append((iid, it, harness, digest))
    with open(OUT, "w", encoding="utf-8") as f:
        f.write("# GENERATED by tools/spec_registry.py -- do not hand-edit.\n")
        f.write(f"# {len(rows)} items. A row's state is decided by "
                f"station/spec_check.py, never written here by hand.\n")
        f.write("items:\n")
        for iid, it, harness, digest in rows:
            f.write(f"  - id: {iid}\n")
            f.write(f"    at: {it['file']}:{it['line']}\n")
            f.write(f"    harness: {harness}\n")
            f.write(f"    text_sha: {digest}\n")
    return len(rows)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="validate only; nonzero exit on any error")
    a = ap.parse_args()
    items, refs, errors = parse(DOCS)
    errors += validate(items, refs)
    by_pref = {}
    for iid in items:
        if "#dup" not in iid:
            by_pref[iid.split("-")[0]] = by_pref.get(iid.split("-")[0], 0) + 1
    print("registry:", " ".join(f"{k} {v}" for k, v in sorted(by_pref.items())),
          f"= {sum(by_pref.values())} items")
    if errors:
        print(f"\n{len(errors)} ERROR(S) — the registry cannot be produced "
              f"around an ambiguity:")
        for e in errors[:40]:
            print("  ", e)
        if len(errors) > 40:
            print(f"   ... and {len(errors) - 40} more")
        return 1
    if not a.check:
        n = emit(items)
        print(f"wrote {os.path.relpath(OUT, ROOT)} — {n} rows")
    return 0


if __name__ == "__main__":
    sys.exit(main())
